import json
from graphrag_sdk import KnowledgeGraph, Ontology
from graphrag_sdk.helpers import extract_json, map_dict_to_cypher_properties
from colorama import init, Fore, Style


class JSONFormattingException(Exception):
    """Exception raised when the JSON structure is invalid."""
    pass

class OntologyFormattingException(Exception):
    """Exception raised when the ontology strcture is invalid."""
    pass

def validate_generated_ontology(ontology_text: str):
    """
    It validates an ontology generated by an LLM. 
    The ontology must be a JSON object provided as text. 
    It throws an exception if one or more errors are found:
        1) 'JSONFormattingException': Exception raised when the JSON structure is invalid.
        2) 'OntologyFormattingException': Exception raised when the ontology strcture is invalid.
    If the ontology is valid, it returns the corresponding JSON object.
    """
    try:
        data = json.loads(extract_json(ontology_text))
    except Exception as ex:
        raise JSONFormattingException(str(ex))
    
    for relation in data["relations"]:
        relation_attrs = relation.get("attributes", [])          
        for attr in relation_attrs:
            attr["unique"] = False          
    
    errors = "" # List containing all the (ontology formatting) errors
    entity_labels_Keys = dict() # Dictionary where the key is the entity label and the value is the name of the 'Key' attribute
    for entity in data["entities"]:
        count_unique_attr = 0
        entity_label = entity.get("label")
        if entity_label is None:
            errors = errors + f"An entity does not have a label - "
            continue
        if entity_label in entity_labels_Keys.keys():
            errors = errors + f"More than one entities have the same '{entity_label}' label - "
            continue
        entity_labels_Keys[entity_label] = ""
        entity_attrs = entity.get("attributes")
        if entity_attrs is None:
            errors = errors + f"The entity '{entity_label}' does not have any attributes - "
            continue
        for attr in entity_attrs:
            name_attr = attr.get("name")
            if name_attr is None:
                errors = errors + f"The entity '{entity_label}' has an attribute without a 'name' - "
                continue
            unique_attr = attr.get("unique")
            if unique_attr is None:
                errors = errors + f"The attribute '{name_attr}' of the entity '{entity_label}' does not have the 'unique' value - "
                continue
            required_attr = attr.get("required")
            if required_attr is None:
                errors = errors + f"The attribute '{name_attr}' of the entity '{entity_label}' does not have the 'required' value - "
                continue
            type_attr = attr.get("type")
            if type_attr is None:
                errors = errors + f"The attribute '{name_attr}' of the entity '{entity_label}' does not have the 'type' value - "
            if unique_attr is True:
                entity_labels_Keys[entity_label] = name_attr
                if required_attr is False:
                    attr["required"] = True
                count_unique_attr += 1
        if count_unique_attr!=1:
            if count_unique_attr==0:
                errors = errors + f"The entity '{entity_label}' does not have the unique attribute - "
            else:
                errors = errors + f"The entity '{entity_label}' has more than one unique attribute - "

    relations_IDS = [] # List containing all the relation ID values. The ID is composed of the relation label and the source/target label.
    for relation in data["relations"]:
        relation_label = relation.get("label")
        if relation_label is None:
            errors = errors + f"A relation does not have a label - "
            continue
        relation_attrs = relation.get("attributes", [])          
        for attr in relation_attrs:
            name_attr = attr.get("name")
            if name_attr is None:
                errors = errors + f"The relation '{relation_label}' has an attribute without a 'name' - "
                continue
            unique_attr = attr.get("unique")
            if unique_attr is None:
                errors = errors + f"The attribute '{name_attr}' of the relation '{relation_label}' does not have the 'unique' value - "
                continue
            required_attr = attr.get("required")
            if required_attr is None:
                errors = errors + f"The attribute '{name_attr}' of the relation '{relation_label}' does not have the 'required' value - "
                continue
            type_attr = attr.get("type")
            if type_attr is None:
                errors = errors + f"The attribute '{name_attr}' of the relation '{relation_label}' does not have the 'type' value - "
            if unique_attr is True:
                if required_attr is False:
                    attr["required"] = True
        
        #SOURCE
        first_iter_source=True
        while(first_iter_source):
            first_iter_source = False        
            source = relation.get("source")
            if source is None:
                errors = errors + f"The relation '{relation_label}' does not have a source entity - "
                break
            source_label = source.get("label")
            if source_label is None:
                errors = errors + f"The source of the relation '{relation_label}' does not have a label - "
                break
            if source_label not in entity_labels_Keys.keys():
                errors = errors + f"The source '{source_label}' of the relation '{relation_label}' does not exist in the entity list - "
                break
            source_attrs = source.get("attributes")   
            if source_attrs is None:
                errors = errors + f"The source '{source_label}' of the relation '{relation_label}' does not have any attributes - "
            count_unique_attr = 0
            for attr in source_attrs:
                name_attr = attr.get("name")
                if name_attr is None:
                    errors = errors + f"The source '{source_label}' of the relation '{relation_label}' has an attribute without a 'name' - "
                    continue
                unique_attr = attr.get("unique")
                if unique_attr is None:
                    errors = errors + f"The source attribute '{name_attr}' of the relation '{relation_label}' does not have the 'unique' value - "
                    continue
                required_attr = attr.get("required")
                if required_attr is None:
                    errors = errors + f"The source attribute '{name_attr}' of the relation '{relation_label}' does not have the 'required' value - "
                    continue
                type_attr = attr.get("type")
                if type_attr is None:
                    errors = errors + f"The source attribute '{name_attr}' of the relation '{relation_label}' does not have the 'type' value - "
                if unique_attr is True:
                    count_unique_attr = count_unique_attr + 1
                    if required_attr is False:
                        attr["required"] = True
                    key_from_dict = entity_labels_Keys[source_label]
                    if name_attr != key_from_dict:
                        errors = errors + f"The source attribute '{name_attr}' of the relation '{relation_label}' is tagged as 'unique' so it should be the keyref of the entity '{source_label}'. However, this keyref does not correspond to the effective key that is '{key_from_dict}' - "
            if count_unique_attr!=1:
                if count_unique_attr==0:
                    errors = errors + f"The source of the relation '{relation_label}' does not have the unique attribute - "
                else:
                    errors = errors + f"The source of the relation '{relation_label}' has more than one unique attribute - "

        #TARGET
        first_iter_target=True
        while(first_iter_target):  
            first_iter_target = False
            target = relation.get("target")
            if target is None:
                errors = errors + f"The relation '{relation_label}' does not have a target entity - "
                break
            target_label = target.get("label")
            if target_label is None:
                errors = errors + f"The target of the relation '{relation_label}' does not have a label - "
                break
            if target_label not in entity_labels_Keys.keys():
                errors = errors + f"The target '{target_label}' of the relation '{relation_label}' does not exist in the entity list - "
            target_attrs = target.get("attributes")   
            if target_attrs is None:
                errors = errors + f"The target '{target_label}' of the relation '{relation_label}' does not have any attributes - "
            count_unique_attr = 0
            for attr in target_attrs:
                name_attr = attr.get("name")
                if name_attr is None:
                    errors = errors + f"The target '{target_label}' of the relation '{relation_label}' has an attribute without a 'name' - "
                    continue
                unique_attr = attr.get("unique")
                if unique_attr is None:
                    errors = errors + f"The target attribute '{name_attr}' of the relation '{relation_label}' does not have the 'unique' value - "
                    continue
                required_attr = attr.get("required")
                if required_attr is None:
                    errors = errors + f"The target attribute '{name_attr}' of the relation '{relation_label}' does not have the 'required' value - "
                    continue
                type_attr = attr.get("type")
                if type_attr is None:
                    errors = errors + f"The target attribute '{name_attr}' of the relation '{relation_label}' does not have the 'type' value - "
                if unique_attr is True:
                    count_unique_attr = count_unique_attr + 1
                    if required_attr is False:
                        attr["required"] = True
                    key_from_dict = entity_labels_Keys[target_label]
                    if name_attr != key_from_dict:
                        errors = errors + f"The target attribute '{name_attr}' of the relation '{relation_label}' is tagged as 'unique' so it should be the keyref of the entity '{target_label}'. However, this keyref does not correspond to the effective key that is '{key_from_dict}' - "
            if count_unique_attr!=1:
                if count_unique_attr==0:
                    errors = errors + f"The target of the relation '{relation_label}' does not have the unique attribute - "
                else:
                    errors = errors + f"The target of the relation '{relation_label}' has more than one unique attribute - "
        
        current_relation_ID = relation_label + "-" + source_label + "-" + target_label + "."
        if current_relation_ID in relations_IDS:
            errors = errors + f"The relation with label '{relation_label}', source label '{source_label}', and target label '{target_label}' is duplicated in the ontology - "
            continue
        relations_IDS.append(current_relation_ID)

    if errors:
        errors = errors + "."
        raise OntologyFormattingException(errors)
    else:
        try:
            _ = Ontology.from_json(data)
        except Exception as ex:
            errors = errors + " - " + str(ex)
            errors = errors + "."
        if errors:
            raise OntologyFormattingException(errors)
        else:
            return data


def get_unique_attribute_entity(label,  text_ontology: str):
    """
    Given an entity label, it returns the name of its unique attribute according to the given ontology.
    """
    name_entity_attrs_unique_schema = []
    entity_schema = get_entity_schema(label, text_ontology)
    if entity_schema is not None:
        entity_attrs_schema = entity_schema.get("attributes")
        name_entity_attrs_unique_schema = [item['name'] for item in entity_attrs_schema if 'name' in item and 'unique' in item and item['unique']==True]
    
    if name_entity_attrs_unique_schema:
        return name_entity_attrs_unique_schema[0]
    else:
        return None
    
def get_required_attributes_entity(label,  text_ontology: str):
    """
    Given an entity label, it returns the names of its required attributes according to the given ontology.
    """
    name_entity_attrs_required_schema = []
    entity_schema = get_entity_schema(label, text_ontology)
    if entity_schema is not None:
        entity_attrs_schema = entity_schema.get("attributes")
        name_entity_attrs_required_schema = [item['name'] for item in entity_attrs_schema if 'name' in item and 'required' in item and item['required']==True]
    
    if name_entity_attrs_required_schema:
        return name_entity_attrs_required_schema
    else:
        return None


def get_entity_schema(label, text_ontology: str):
    """
    Returns the entity object schema retrived from the given ontology.
    """
    entity_schema = None
    for entity_ontology in text_ontology['entities']:
        if entity_ontology.get("label") == label:
            entity_schema = entity_ontology
            break
    return entity_schema



def verify_entity(json_entity, text_ontology: str, errors):
    """
    Verifies that the input entity JSON object conforms to the required ontology structure for entity and relation extraction. 
    It returns the list of errors.
    """

    entity_label = json_entity['label']
    entity_schema = get_entity_schema(entity_label, text_ontology)
    entity_attrs_schema = entity_schema.get("attributes")
    name_entity_attrs_schema = [item['name'] for item in entity_attrs_schema if 'name' in item]

    entity_attrs = json_entity.get("attributes")
    name_entity_attrs_required_schema = get_required_attributes_entity(entity_label, text_ontology)
    if entity_attrs is not None:
        for key, value in entity_attrs.items():
            if key not in name_entity_attrs_schema:
                errors = errors + f"The attribute '{key}' of the entity '{entity_label}' does not exist in the ontology - "
        for name in name_entity_attrs_required_schema:
            if name not in entity_attrs.keys():
                errors = errors + f"The attribute '{name}' of the entity '{entity_label}' is required in the ontology but is missing in the JSON data - "


    
def get_required_attributes_relation(label, source_label, target_label, text_ontology: str):
    """
    Given a relation label, it returns the names of its required attributes according to the given ontology.
    """
    name_relation_attrs_required_schema = []
    relation_schema = get_relation_schema(label, source_label, target_label, text_ontology)
    if relation_schema is not None:
        relation_attrs_schema = relation_schema.get("attributes")
        name_relation_attrs_required_schema = [item['name'] for item in relation_attrs_schema if 'name' in item and 'required' in item and item['required']==True]
    
    if name_relation_attrs_required_schema:
        return name_relation_attrs_required_schema
    else:
        return None


def get_relation_schema(label, source_label, target_label, text_ontology: str):
    """
    Returns the relation object schema retrived from the given ontology.
    """
    relation_schema = None
    for relation_ontology in text_ontology['relations']:
        if relation_ontology.get("label") == label and relation_ontology.get("source").get("label") == source_label and relation_ontology.get("target").get("label") == target_label:
            relation_schema = relation_ontology
            break
    return relation_schema


def verify_relation(relation, entities, text_ontology, errors):
    """
    Verifies that the input relation JSON object conforms to the required ontology structure for entity and relation extraction. 
    It returns the list of errors.
    """
    relation_label = relation['label']

    source_label = None
    source = relation.get("source")
    if source is None:
        errors = errors + f"The source entity of the relation '{relation_label}' is missing - "
    else:
        source_label = source.get("label")
        if source_label is None:
            errors = errors + f"The source entity of the relation '{relation_label}' has not a label - "

    target_label = None
    target = relation.get("target")
    if target is None:
        errors = errors + f"The target entity of the relation '{relation_label}' is missing - "
    else:
        target_label = target.get("label")
        if target_label is None:
                errors = errors + f"The target entity of the relation '{relation_label}' has not a label - "

    if source_label is None or target_label is None:
        return


    relation_schema = get_relation_schema(relation_label, source_label, target_label, text_ontology)
    relation_attrs_schema = relation_schema.get("attributes")
    name_relation_attrs_schema = [item['name'] for item in relation_attrs_schema if 'name' in item]

    relation_attrs = relation.get("attributes")
    name_relation_attrs_required_schema = get_required_attributes_relation(relation_label,source_label, target_label, text_ontology)
    if relation_attrs is not None:
        for key, value in relation_attrs.items():
            if key not in name_relation_attrs_schema:
                errors = errors + f"The attribute '{key}' of the relation '{relation_label}' does not exist in the ontology - "
        for name in name_relation_attrs_required_schema:
            if name not in relation_attrs.keys():
                errors = errors + f"The attribute '{name}' of the relation '{relation_label}' is required in the ontology but is missing in the JSON data - "

    first_iteration_source = True
    while(first_iteration_source):
        first_iteration_source = False
        source_schema = get_entity_schema(source_label, text_ontology)
        if source_schema is None:
            errors = errors + f"The source entity with label '{source_label}' of the relation '{relation_label}' does not exist in the ontology - "
            break
        source_attrs = source.get("attributes")
        if source_attrs is None:
            errors = errors + f"The source entity of the relation '{relation_label}' does not have any attributes - "
            break

        name_key_attr = get_unique_attribute_entity(source_label, text_ontology)
        source_keyref_value = None
        for key, value in source_attrs.items():
            if key == name_key_attr:
                source_keyref_value = value
                break
        if source_keyref_value is None:
            errors = errors + f"The source entity of the relation '{relation_label}' does not have the keyref value - "
            break
        found=False
        for entity in entities:
            entity_label = entity.get("label")
            if entity_label is not None:
                if entity_label == source_label:
                    for key, value in entity.get("attributes").items():
                        if key == name_key_attr:
                            if value == source_keyref_value:
                                found = True
                                break
                    if found:
                        break
        if found==False:
            errors = errors + f"The source entity of the relation '{relation_label}' does not exist in the entity list - "


    first_iteration_target=True
    while(first_iteration_target):
        first_iteration_target = False
        target_schema = get_entity_schema(target_label, text_ontology)
        if target_schema is None:
            errors = errors + f"The target entity with label '{target_label}' of the relation '{relation_label}' does not exist in the ontology - "
            break
        target_attrs = target.get("attributes")
        if target_attrs is None:
            errors = errors + f"The target entity of the relation '{relation_label}' does not have any attributes - "
            break

        name_key_attr = get_unique_attribute_entity(target_label, text_ontology)
        target_keyref_value = None
        for key, value in target_attrs.items():
            if key == name_key_attr:
                target_keyref_value = value
                break
        if target_keyref_value is None:
            errors = errors + f"The target entity of the relation '{relation_label}' does not have the keyref value - "
            break
        found=False
        for entity in entities:
            entity_label = entity.get("label")
            if entity_label is not None:
                if entity_label == target_label:
                    for key, value in entity.get("attributes").items():
                        if key == name_key_attr:
                            if value == target_keyref_value:
                                found = True
                                break
                    if found:
                        break
        if found==False:
            errors = errors + f"The target entity of the relation '{relation_label}' does not exist in the entity list - "


                            

def check_duplicated_relation(json_relations, text_ontology, errors):
    """
    Verifies if there are duplicated relations (i.e. same label, source label, target label, and the same values for the keyref attributes)
    It returns the list of errors.
    """
    relations_IDs = [] # Lista containing all the relation IDs. The identify of a relation is composed of its label, its source label and keyref, and its target label and keyref.
    for relation in json_relations:
        ID = ""
        relation_label = relation.get("label")
        if relation_label is None:
           continue
        ID = f"relation_label:'{relation_label}',"
        source = relation.get("source")
        if source is None:
            continue
        source_label = source.get("label")
        if source_label is None:
            continue
        ID = ID + f"source_label:'{source_label}',"
        target = relation.get("target")
        if target is None:
            continue
        target_label = target.get("label")
        if target_label is None:
            continue
        ID = ID + f"target_label:'{target_label}',"
        
        if relation_label is not None and source_label is not None and target_label is not None:
            for relation_ontology in text_ontology['relations']:
                relation_label_ontology = relation_ontology.get("label")
                source_ontology = relation_ontology.get("source")
                source_label_ontology = source_ontology.get("label")
                target_ontology = relation_ontology.get("target")
                target_label_ontology = target_ontology.get("label")

                if relation_label_ontology is not None and source_label_ontology is not None and target_label_ontology is not None:
                    if relation_label_ontology == relation_label and source_label_ontology == source_label and target_label_ontology==target_label:
                        relation_ontology_schema = relation_ontology
                        break
            if relation_ontology_schema is None:
                continue

            source_key_attrname = None
            source_schema = relation_ontology_schema.get("source")
            for source_attr_schema in source_schema.get("attributes", []):
                if source_attr_schema.get("unique") == True:
                    source_key_attrname = source_attr_schema.get("name")
                    break
            target_key_attrname = None
            if relation_ontology_schema is not None:
                target_schema = relation_ontology_schema.get("target")
                for target_attr_schema in target_schema.get("attributes", []):
                    if target_attr_schema.get("unique") == True:
                        target_key_attrname = target_attr_schema.get("name")
                        break

            if source_key_attrname is None or target_key_attrname is None:
                continue

            found_source_key = False
            source_attrs = source.get("attributes")
            if source_attrs is not None:
                for key, value in source_attrs.items():
                    if key == source_key_attrname:
                        found_source_key = True
                        ID = ID + f"source_keyref_value:'{value}',"
                        break
            if found_source_key==False:
                continue


            found_target_key = False
            target_attrs = target.get("attributes")
            if target_attrs is not None:
                for key, value in target_attrs.items():
                    if key == target_key_attrname:
                        found_target_key = True
                        ID = ID + f"target_keyref_value:'{value}'."
                        break
            if found_target_key==False:
                continue
        
            relations_IDs.append(ID)
    seen = set()
    duplicated = set(x for x in relations_IDs if x in seen or seen.add(x))
    errors = errors + f"The following relations are duplicated. '{list(duplicated)}' - "


def get_dict_label_nameKeyAttribute(text_ontology: str):
    """
    Returns a dictionary where the key is the entity label and the value the name of the unique attribute (aka key attribute)
    """
    label_name_key = dict() # Dictionary where the key is the entity label and the value the name of the unique attribute (aka key attribute)
    for entity_ontology in text_ontology['entities']:
        entity_ontology_label = entity_ontology.get("label")
        attrs = entity_ontology.get("attributes", [])
        for attr in attrs:
            if attr.get("unique")==True:
                label_name_key[entity_ontology_label] = attr.get("name")
                break
    return label_name_key



def check_duplicated_entity(json_entities, text_ontology, errors):
    """
    Verifies if there are duplicated entities (i.e. same label and the same value for the key attribute)
    It returns the list of errors.
    """
    label_name_key = get_dict_label_nameKeyAttribute(text_ontology)
    for key, value in label_name_key.items():
        entities_label = [] # List containing all the entities with the same label (ie. the current 'key' of the dictionary)
        for entity in json_entities:
            if entity.get("label") == key:
                entities_label.append(entity)
        IDs = []
        for entity in entities_label:
            for attr_key, attr_value in entity.get("attrs").items():
                if attr_key == value: # if it is the 'key' attribute
                    IDs.append(attr_value) 
                    break
        seen = set()
        duplicated = set(x for x in IDs if x in seen or seen.add(x))
        errors = errors + f"For the entity label '{key}' there are the following duplicates '{list(duplicated)}' - "
        
    

                

def get_json_data(text_json : str, ontology, text_ontology: str):
    """
    Verifies that the input JSON conforms to the required ontology structure for entity and relation extraction. 
    If the JSON is valid, returns the JSON object.
    If the JSON is invalid, an exception will be thrown.
    """
    json_object = json.loads(extract_json(text_json))

    errors = ""
    for json_entity in json_object["entities"]:
        try:
            if "label" not in json_entity:
                errors = errors + "There is an entity without a label - "
                continue
            entity = ontology.get_entity_with_label(json_entity["label"])
            if entity is None:
                errors = errors + f"Entity with label '{json_entity['label']}' not found in ontology - "
                continue
            errors = verify_entity(json_entity, text_ontology, errors)
            unique_attributes_schema = [attr for attr in entity.attributes if attr.unique]
            unique_attributes = {
                attr.name: (
                    json_entity["attributes"][attr.name] if attr.name in json_entity["attributes"] else ""
                )
                for attr in unique_attributes_schema
            }
            unique_attributes_text = map_dict_to_cypher_properties(unique_attributes)
            non_unique_attributes = {
                attr.name: json_entity["attributes"][attr.name]
                for attr in entity.attributes
                if not attr.unique and attr.name in json_entity["attributes"]
            }
            non_unique_attributes_text = map_dict_to_cypher_properties(
                non_unique_attributes
            )
        except Exception as e:
            if "label" in json_entity:
                errors = errors + f"Error '{e}' while validating the entity '{json_entity.get("label")}' - "
            else:
                errors = errors + f"Error '{e}' while validating an entity' - "
            continue
    errors = check_duplicated_entity(json_object["entities"], text_ontology, errors)


    for relation in json_object["relations"]:
        try:
            if "label" not in relation:
                errors = errors + "There is a relation without a label - "
                continue
            relations = ontology.get_relations_with_label(relation["label"])
            if len(relations) == 0:
                errors = errors + f"Relation with label '{relation['label']}' not found in ontology - "
                continue
            errors = verify_relation(relation, text_ontology, errors)
            source_unique_attributes = (
                relation["source"]["attributes"]
                if "source" in relation and "attributes" in relation["source"]
                else {}
            )
            source_unique_attributes_text = map_dict_to_cypher_properties(
                source_unique_attributes
            )

            target_unique_attributes = (
                json_object["target"]["attributes"]
                if "target" in relation and "attributes" in relation["target"]
                else {}
            )
            target_unique_attributes_text = map_dict_to_cypher_properties(
                target_unique_attributes
            )

            relation_attributes = (
                map_dict_to_cypher_properties(json_object["attributes"])
                if "attributes" in json_object
                else {}
            )
        except Exception as e:
            if "label" in relation:
                errors = errors  + f"Error '{e}' while validating the relation '{relation.get("label")}' - "
            else:
                errors = errors + f"Error '{e}' while validating a relation - "
            continue

    errors = check_duplicated_relation(json_object["relations"], text_ontology, errors)
   
    if errors:
        errors = errors + "."
        raise Exception(errors)
    else:
        return json_object
                



            
        

                
